### PR TITLE
Hoist @property rules to root level

### LINKED ISSUE #325: Can CSS Houdini styles be used?
Before
```
  @property --angle {
    syntax: '<angle>';
    inherits: true;
    initial-value: 0turn;
  }

  @keyframes spin {
    to {
      --angle: 1turn;
    }
  }

  animation: spin 3s linear infinite;
```
It works in @emotion/styled
Now it's not working, need help~

### PR DESCRIPTION
**Pull request by jantimon**
This PR addresses issue #325 where CSS Houdini's `@property` rules were not working correctly when nested inside selectors. According to CSS specs, `@property` rules must appear at the top level of a stylesheet to function properly.

The fix **modifies the CSS stringification** to identify `@property` rules and hoist them to the root level, maintaining compatibility with other CSS processors like Emotion/styled-components that automatically handle this hoisting.

**Testing**: Added test case to verify `@property` hoisting behavior.

Fixes #325

### CODE REVIEW

File: packages/yak-swc/css_in_js_parser/src/to_css.rs [hunk 1]
```diff
@@ -38,12 +66,33 @@ pub fn to_css(declarations: &[Declaration]) -> String {
...
+  // Close all regular scopes with proper indentation
   for i in (0..previous_scopes.len()).rev() {
-    css.push_str(&format!("\n{}}}", "  ".repeat(i)));
+    regular_css.push_str(&format!("\n{}}}", "  ".repeat(i)));
   }
 
-  css
+  // Combine hoisted CSS and regular CSS
+  if !hoisted_css.is_empty() && !regular_css.is_empty() {
+    format!("{}{}", hoisted_css, regular_css)
```
[the remark this answers is not in the document]
Comment (jantimon) [reply packages/yak-swc/css_in_js_parser/src/to_css.rs:81]: as you can see in the test that's already the case

File: packages/yak-swc/css_in_js_parser/src/to_css.rs [hunk 2]
```diff
@@ -38,12 +66,33 @@ pub fn to_css(declarations: &[Declaration]) -> String {
...
+  } else {
+    hoisted_css + &regular_css
+  }
+}
+
+/// If according to the css spec the inner scope of declaration must not be nested
+/// (e.g. @property) return that scope
+fn get_non_nestable_declarations(declaration: &Declaration) -> Option<CssScope> {
+  for scope in &declaration.scope {
+    if scope.scope_type == ScopeType::AtRule && (scope.name.starts_with("@property")) {
```
Comment (Mad-Kat) [inline packages/yak-swc/css_in_js_parser/src/to_css.rs:91]: Should we also do this for keyframes?

File: packages/yak-swc/css_in_js_parser/src/to_css.rs [hunk 3]
```diff
@@ -1,18 +1,46 @@
 //! Converts a list of CSS declarations to a CSS string
-use crate::{CssScope, Declaration};
+use crate::{CssScope, Declaration, ScopeType};
 
 pub fn to_css(declarations: &[Declaration]) -> String {
```
Comment (Mad-Kat) [inline packages/yak-swc/css_in_js_parser/src/to_css.rs:4]: A small documentation what this function does would be nice

**Review by Mad-Kat — APPROVED** [review]
Just some ideas for improvement, but it works and can be merged at your discretion

File: packages/yak-swc/css_in_js_parser/src/to_css.rs (hunk 2 above)
Comment (jantimon) [reply packages/yak-swc/css_in_js_parser/src/to_css.rs:91]: yes but it would require some tweaking

`@property --foo {` has 1 scope

but

`@keyframes { from {` has 2 scopes

that's why I didn't implement it right away but used variable/function names which allow such an extension

**Review by Mad-Kat — APPROVED** [review]
